### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by hindicoder3**

### CODE REVIEW

**Comment by RayBytes** [comment]
Good job, looks really good. However for some reason the ID keeps returning void with this code. Will have to investigate.

**Comment by RayBytes** [comment]
I'll look into it tmrw morning

**Comment by RayBytes** [comment]
Also you seem to use the BASE_PROMPT variable sometimes and sometimes not, there are still urls in the code which still dont use it

**Comment by hindicoder3** [comment]
> Also you seem to use the BASE_ENDPOINT variable sometimes and sometimes not, there are still urls in the code which still dont use it

FIxed, thank you!



> Good job, looks really good. However for some reason the ID keeps returning void with this code. Will have to investigate.

Oh, that's weird...  gonna look at it right now

**Comment by hindicoder3** [comment]
now it works perfectly fine

**Comment by hindicoder3** [comment]
sorry for that mess in commits

**Comment by RayBytes** [comment]
If you can fix that, I can merge this. Don't see any other issues.

**Comment by hindicoder3** [comment]
> If you can fix that, I can merge this. Don't see any other issues.

already fixed in #e026587

**Comment by RayBytes** [comment]
> > If you can fix that, I can merge this. Don't see any other issues.
> 
> already fixed in [e026587](https://github.com/RayBytes/bing-image-gen/commit/e026587a0d019c9c1d3b2f3f28ca007368d884bc)

it has not been

**Comment by RayBytes** [comment]
Look at the review.

**Pull request merged**
